#!/bin/sh -e

PATH=/sbin:/bin:/usr/sbin:/usr/bin 

case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

apt-key add /opt/ossxp/conf/public.key

SCRIPT=/opt/ossxp/install/base.py
[ -x $SCRIPT ] && $SCRIPT config

cat <<EOF
[1mrun this command as root:
[1m[44m	/opt/ossxp/install/base.py install config
[0m
EOF
